### PR TITLE
[WIP] Add new content to home page - internal

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #957

content/design still WIP, posting for feedback/suggestions

image

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I'm not sure this sentence makes sense since it's not true. 

> "Carbon was built on the DUO foundation.... " 

@Clay-Crenshaw @trtate we need a better wording for this. Maybe Carbon will be built, or Carbon was built on the IBM Design Language and will be updated/evolving to be built on DUO?

**Comment by shinytoyrobots** [comment]
We aren't externalizing the Duo name. Carbon has been, and will continue to be, built on the IBM Design Language (and will thus update as that Design Language updates).

**Comment by claycrenshaw** [comment]
I can do a quick cleanup pass on the copy.

**Comment by alisonjoseph** [comment]
closing this since we are creating a separate page instead per conversation with @claycrenshaw

**Pull request closed without merging**
